#!/bin/bash

info() {
  printf "[\033[00;34mINFO\033[0m] $1\n"
}

success() {
  printf "[\033[00;32mOK\033[0m] $1\n"
}

error() {
  printf "[\033[00;31mERROR\033[0m] $1\n"
}

big_info() {
  printf "\e[34m
==============================
$1
==============================\n\e[m"
}

bootstrap() {
    info "start install tools"
    install_all
}

install_all() {
    install_alp
}

install_alp() {
  info 'Installing alp'
  wget https://github.com/tkuchiki/alp/releases/download/v1.0.9/alp_linux_amd64.zip
  unzip alp_linux_amd64.zip
  sudo mv alp /usr/bin/

  rm alp_linux_amd64.zip

  success "install alp"
}


bootstrap
