#!/bin/bash

info() {
  printf "[\033[00;34mINFO\033[0m] $1\n"
}

success() {
  printf "[\033[00;32mOK\033[0m] $1\n"
}

error() {
  printf "[\033[00;31mERROR\033[0m] $1\n"
}

big_info() {
  printf "\e[34m
==============================
$1
==============================\n\e[m"
}

bootstrap() {
  info "start install tools"
  install_all

  info "start git init"
  git_init

  info "start git config"
  git_config

  info "download Makefile"
  download_makefile

}

install_all() {
    install_alp
    install_pt_query_digest
    install_notify_slack
}

install_alp() {
  info 'Installing alp'
  wget https://github.com/tkuchiki/alp/releases/download/v1.0.9/alp_linux_amd64.zip
  unzip alp_linux_amd64.zip
  sudo mv alp /usr/bin/

  rm alp_linux_amd64.zip

  success "install alp"
}

install_pt_query_digest() {
  info 'Install pt-query-digest'
  wget https://github.com/percona/percona-toolkit/archive/refs/tags/v3.3.1.tar.gz
  tar zxvf v3.3.1.tar.gz
  sudo mv ./percona-toolkit-3.3.1/bin/pt-query-digest /usr/bin/

  rm v3.3.1.tar.gz
  rm -rf percona-toolkit-3.3.1

  success "install pt-query-digest"
}

install_notify_slack() {
  info 'Install notify_slack'
  NOTIFY_SLACKDIR="/tmp/notify_slack"
  mkdir ${NOTIFY_SLACKDIR}
  cd ${NOTIFY_SLACKDIR}
  wget https://github.com/catatsuy/notify_slack/releases/download/v0.4.13/notify_slack-linux-amd64.tar.gz
  tar zxvf notify_slack-linux-amd64.tar.gz
  sudo mv notify_slack /usr/bin/
  rm -rf ${NOTIFY_SLACKDIR}
  success "install notify_slack"

}


git_init() {
  git init
  ssh-keygen && cat $HOME/.ssh/id_rsa.pub

  printf "\e[34mCopy this SSH key (https://github.com/settings/ssh/new)\e[m\n"
  while :
  do
    read -p "Added SSH key? (y/n)" input
    if [ "$input" = "y" ]; then
      echo "Continue to setup!"
      break
    elif [ "$input" = "n" ]; then
      echo "Please Add SSH Key."
    fi
  done

  ssh -T git@github.com
}

git_config() {
  git config --global user.email "gongqi-zhen@gmail.com"
  git config --global user.name "gongqi-zhen"

  git config --global core.editor 'vim -c "set fenc=utf-8"'
}

download_makefile() {
  curl -O https://raw.githubusercontent.com/gongqi-zhen/isucon-magic-powder/main/Makefile
}

bootstrap
